KITS/urls.py
# from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'KITS'
name: object
urlpatterns = [
    path('', views.home, name='home'),
    path('list_history/', views.list_history, name='list_history'),
    path('study_list/', views.study_list, name='study_list'),
    path('study/<int:pk>/study_detail/', views.study_detail, name='study_detail'),
    path('study/<int:pk>/study_detail/kit_edit/', views.kit_edit, name='kit_edit_from_study'),
    path('study/<int:pk>/study_detail/study_detail_seeallkits/', views.study_detail_seeallkits,
         name='study_detail_seeallkits'),
    path('study/<int:pk>/study_detail/study_edit', views.study_edit, name='study_detail_study_edit'),

    path('create_study/', views.create_study, name='create_study'),
    path('study/<int:pk>/edit', views.study_edit, name='study_edit'),
    path('study/<int:pk>/archive/', views.study_archive, name='study_archive'),
    path('study/<int:pk>/create_req', views.create_req, name='create_req'),
    path('study/<int:pk>/study_detail/req_edit', views.req_edit, name='req_edit'),

    path('kit_list/kit_addtype/', views.kit_addkittype, name='kit_addkittype'),
    path('kit_list/kit_addlocation/', views.kit_addlocation, name='kit_addlocation'),

    path('kit_list/', views.kit_list, name='kit_list'),
    path('kit_list/<int:pk>/kit_edit/', views.kit_edit, name='kit_edit'),

    path('kit_list/<int:pk>/delete/', views.kit_delete, name='kit_delete'),
    path('kit_list/<int:pk>/kit_addkitinstance/', views.kit_addkitinstance, name='kit_addkitinstance'),

    path('report/', views.report, name='report'),
    path('report/report_expiredkits/', views.report_expiredkits, name='report_expiredkits'),

    path('report/report_activestudies/', views.report_activestudies, name='report_activestudies'),
    path('report/user_list/', views.user_list, name='user_list'),
    path('report/<int:pk>/report_userstudies/', views.report_userstudies, name='report_userstudies'),
    path('report/report_expiredkits/studies', views.report_expiredkits_studies, name='report_expiredkits_studies'),
    path('report/report_storageusage/', views.report_storageusage, name='report_storageusage'),
    path('report/report_studyactivity/', views.report_studyactivity, name='report_studyactivity'),

    path('study/<int:pk>/study_detail/kit_ordering', views.kit_ordering, name='kit_ordering'),
    path('study/<int:pk>/kit_ordering_add/', views.kit_ordering_add, name='kit_ordering_add'),

    path('help/', views.help_page, name='help'),
    path('refresh/', views.refresh, name='refresh'),

    path('kit_checkout/', views.kit_checkout, name='kit_checkout'),
    path('kitinstance_statusedit/<uuid:pk>', views.kitinstance_statusedit, name='kitinstance_statusedit'),
    path('kitinstance_demolish/<uuid:pk>/', views.kitinstance_demolish, name='kitinstance_demolish'),

    path('export_expiredkits/', views.export_expiredkits, name='export_expiredkits'),
    path('export_studieswithexpiredkits/', views.export_studieswithexpiredkits, name='export_studieswithexpiredkits'),
    path('export_user/<int:pk>', views.export_user, name='export_user'),


]

KITS_Project/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('KITS/', include('KITS.urls')),
    path('', RedirectView.as_view(url='KITS/')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Django site authentication URLs (login, logout, password reset)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls'))
]

KITS/forms.py
from django import forms
from .models import KitInstance, Kit, Study, Location, Requisition, KitOrder, User


class StudyForm(forms.ModelForm):
    class Meta:
        model = Study
        fields = (
            'id', 'IRB_number', 'pet_name', 'comment', 'sponsor_name', 'status',
            'start_date', 'end_date')


class RequisitionForm(forms.ModelForm):
    class Meta:
        model = Requisition
        fields = '__all__'
        exclude = ('study',)


class KitForm(forms.ModelForm):
    class Meta:
        model = Kit
        fields = (
            'IRB_number', 'type_name', 'description', 'date_added', 'id',)


class KitIDForm(forms.ModelForm):
    class Meta:
        model = Kit
        fields = ('id',)


class KitInstanceForm(forms.ModelForm):
    class Meta:
        model = KitInstance
        fields = '__all__'
        exclude = ('created_date', 'checked_out_date', 'status', 'kit',)
        # child_model = Kit
        # child_form_class = KitIDForm


class KitOrderForm(forms.ModelForm):
    class Meta:
        model = KitOrder
        fields = '__all__'
        exclude = ('study',)


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = '__all__'


class KitInstanceEditForm(forms.ModelForm):
    KIT_STATUS = (
        ('c', 'Checked Out'),
    )

    status = forms.TypedChoiceField(choices=KIT_STATUS, coerce=str, initial=1)

    class Meta:
        model = KitInstance
        fields = ("status",)


class KitInstanceDemolishForm(forms.ModelForm):
    KIT_STATUS = (
        ('d', 'Demolished'),
    )

    status = forms.TypedChoiceField(choices=KIT_STATUS, coerce=str, initial=1)

    class Meta:
        model = KitInstance
        fields = ['status']


class ExpiredReportDownloadForm(forms.ModelForm):
    KIT_STATUS = (
        ('e', 'Expired'),
    )

    status = forms.TypedChoiceField(choices=KIT_STATUS, coerce=str, initial=1)

    class Meta:
        model = KitInstance
        fields = ['scanner_id', 'expiration_date']

    class Meta1:
        model = Kit
        fields = ['type_name', 'IRB_number']


class UserReportForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'


class AllKitsForm(forms.ModelForm):
    class Meta:
        model = Study
        fields = '__all__'


'''
    class Meta1:
        model = Kit
        fields = '__all__'

    class Meta2:
        model = KitInstance
        fields = '__all__'
'''

KITS/views.py
from django.contrib.auth.decorators import login_required
from .forms import *
from .models import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.db.models import Count, Max, Q
from .filters import LocationFilter, StudyFilter, KitFilter, KitReportFilter, KitInstanceFilter
from django.contrib.auth import get_user_model
from django.dispatch import receiver
from simple_history.signals import post_create_historical_record
from datetime import datetime, timedelta, date
from django.contrib import messages
import csv
from django.http import HttpResponse
from .reports import query_active_studies, validate_date, query_checked_out_kits, query_demolished_kits, \
    storage_tables, storage_data, query_study_activity
from .datavisualization import bar_graph_kit_activity, storage_graph, bar_graph_study_activity
from django.http import HttpResponseRedirect


@receiver(post_create_historical_record)
def post_create_historical_record_callback(sender, **kwargs):
    t_user_t = kwargs["history_user"]

    complete_object = " ".join([str(kwargs["instance"]), str(type(kwargs["instance"]))])
    print(kwargs["history_instance"])
    user_history_instance = \
        UserHistory.objects.create_user_history(t_user_t, complete_object, str(kwargs["history_instance"]),
                                                kwargs["history_date"])
    user_history_instance.save()
    print("Sent after saving historical record")


@login_required
def user_list(request):
    user = get_user_model()
    users = user.objects.all()

    return render(request, 'KITS/user_list.html', {'users': users})


@login_required
def report_userstudies(request, pk):
    in_pk = pk

    # get the username back
    user = get_user_model()
    users = user.objects.all()
    # username is from filter

    user = users.filter(pk=in_pk)
    user_str = user[0]

    # Set default date when user first clicks on active studies reports button
    startdate = date.today() - timedelta(days=30)
    enddate = date.today()

    if request.POST:
        startdate = request.POST['startdate']
        enddate = request.POST['enddate']

        # Check if user's date input are correct
        message = validate_date(startdate, enddate)

        # If user's input are not correct, return error page with the message
        if not message:
            message = validate_date(startdate, enddate)
            messages.error(request, message)
            return redirect('KITS:report_userstudies')
        elif message:
            # Convert date string to date time object
            date_format = "%m-%d-%Y"
            startdate = datetime.strptime(startdate, date_format).date()
            enddate = datetime.strptime(enddate, date_format).date()

    # Need to constrain to the history_user_id, date range, change type (created, changed, deleted)
    qs = Study.history.all()
    qs = qs.filter(history_user_id=in_pk)
    start_dt = datetime.combine(startdate, datetime.min.time())
    end_dt = datetime.combine(enddate, datetime.min.time())

    for elem in qs:
        if elem.history_date.date() < start_dt.date() or elem.history_date.date() > end_dt.date():
            qs = qs.exclude(history_id=elem.history_id)
    qs_changed = qs
    qs_deleted = qs
    qs = qs.filter(history_type='+')
    qs_changed = qs_changed.filter(history_type='~')
    qs_deleted = qs_deleted.filter(history_type='-')

    context = {
        "queryset": qs,
        "queryset_changed": qs_changed,
        "queryset_deleted": qs_deleted,
        "user": user_str,
        "startdate": startdate,
        "enddate": enddate,
    }
    return render(request, "KITS/report_userstudies.html", context)


now = timezone.now()


def index(request):
    return render(request, 'registration/login.html')


def login(request):
    return render(request, 'registration/login.html',
                  {'kits': login})


def logout(request):
    return render(request, 'registration/logout.html',
                  {'kits': logout})


def home(request):
    refresh(request)
    return render(request, 'KITS/home.html')


@login_required
def list_history(request):
    queryset = KitInstance.objects.raw("SELECT * FROM KITS_historicalkitinstance")
    context = {
        "queryset": queryset,
    }
    return render(request, "KITS/list_history.html", context)


@login_required
def study_list(request):
    studies = Study.objects.all()

    # Filter bar
    study_filter = StudyFilter(request.GET, queryset=Study.objects.all())
    if request.GET:
        studies = study_filter.qs

    return render(request, 'KITS/study_list.html', {'studies': studies, 'study_filter': study_filter})


@login_required
def study_detail(request, pk):
    study = get_object_or_404(Study, pk=pk)

    kits = Kit.objects.filter(IRB_number=pk).annotate(
        no_of_kits=Count('kit', filter=Q(kit__status='a'))) \
        .annotate(no_of_kits_exp=Count('kit', filter=Q(kit__status='e'))) \
        .annotate(exp=Max('kit__expiration_date'))

    req = Requisition.objects.filter(study=pk)
    if req.exists():
        req_exist = True
        type_qs = Requisition.objects.filter(study=pk).values('type')
        type_list = type_qs[0]['type']
        req = Requisition.objects.filter(study=pk).values(type_list)
        req = req[0][type_list]
    else:
        req_exist = False
        req = 'No requisition details have been added.'

    kit_order = KitOrder.objects.filter(study=pk)
    if kit_order.exists():
        kit_order_exist = True
        type_qs = KitOrder.objects.filter(study=pk).values('type')
        type_list = type_qs[0]['type']
        kit_order = KitOrder.objects.filter(study=pk).values(type_list)
        kit_order = kit_order[0][type_list]

    else:
        kit_order_exist = False
        kit_order = "No order details have been added."

    kit_exist = str(kits)
    if kit_exist == '<QuerySet []>':
        kit_exist = 'False'
    else:
        kit_exist = 'True'

    return render(request, 'KITS/study_detail.html', {'study': study, 'kits': kits, 'req': req, 'kit_order': kit_order,
                                                      'kit_order_exist': kit_order_exist, 'kit_exist': kit_exist,
                                                      'req_exist': req_exist})


@login_required
def study_detail_seeallkits(request, pk):
    refresh(request)
    study = get_object_or_404(Study, pk=pk)

    status = 'a or e'
    kits = KitInstance.objects.filter(kit__IRB_number=pk).filter(status__in=status).order_by('kit__id',
                                                                                             'expiration_date')

    return render(request, 'KITS/study_detail_seeallkits.html', {'study': study, 'kits': kits})


@login_required
def create_study(request):
    if request.method == "POST":
        form = StudyForm(request.POST)
        if form.is_valid():
            new_study = form.save(commit=False)
            new_study.create_date = timezone.now()
            new_study.save()
            studies = Study.objects.filter(start_date__lte=timezone.now())
            return render(request, 'KITS/study_list.html',
                          {'studies': studies})
    else:
        form = StudyForm()
    return render(request, 'KITS/create_study.html', {'form': form})


@login_required
def study_edit(request, pk):
    # To redirect to the study details page if the request came from the study details page
    test = request
    if 'study_detail' in str(test):
        test = 'study_detail'

    study = get_object_or_404(Study, pk=pk)

    if request.method == "POST":
        # update
        form = StudyForm(request.POST, instance=study)
        if form.is_valid():
            study = form.save(commit=False)
            study.updated_date = timezone.now()
            study.save()
            study = Study.objects.filter(start_date__lte=timezone.now())

            if test == 'study_detail':
                return redirect('KITS:study_detail', pk=pk)
            else:
                return render(request, 'KITS/study_list.html',
                              {'studies': study})

    else:
        # edit
        form = StudyForm(instance=study)
        return render(request, 'KITS/study_edit.html', {'form': form})


@login_required
def study_archive(request, pk):
    study = get_object_or_404(Study, pk=pk)
    study.status = 'Closed'
    study.save()

    message = "The study's status has changed to 'closed' and was put into archive."
    messages.success(request, message)
    return redirect('KITS:study_list')


@login_required
def create_req(request, pk):
    study = get_object_or_404(Study, pk=pk)

    if request.method == "POST":
        form = RequisitionForm(request.POST, request.FILES)
        if form.is_valid():
            new_req = form.save(commit=False)
            new_req.save()
            return redirect('KITS:study_detail', pk=pk)
    else:
        form = RequisitionForm()
    return render(request, 'KITS/create_req.html', {'form': form, 'study': study})


@login_required
def req_edit(request, pk):
    req = get_object_or_404(Requisition, pk=pk)

    if request.method == "POST":
        form = RequisitionForm(request.POST, request.FILES, instance=req)
        if form.is_valid():
            req = form.save(commit=False)
            req.update_date = timezone.now()
            req.save()
            return redirect('KITS:study_detail', pk=pk)
    else:
        # edit
        form = RequisitionForm(instance=req)
    return render(request, 'KITS/req_edit.html', {'form': form})


@login_required
def kit_addkittype(request):
    if request.method == "POST":
        form = KitForm(request.POST)
        if form.is_valid():
            new_kit = form.save(commit=False)
            new_kit.created_date = timezone.now()
            new_kit.save()
            Kit.objects.filter(date_added__lte=timezone.now())
            return redirect('KITS:kit_list')
    else:
        form = KitForm()

templates/KITS/create_req.html
<!DOCTYPE html>
<html lang="en">
{% extends 'KITS/base.html' %}
{% block content %}

    <div class="container-fluid">
        <H2>Study {{ study.IRB_number }}: Add Requisition Information</H2>
        <hr>

        <form method="POST" class="study-form" enctype="multipart/form-data">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Confirm</button>
        </form>
    </div>
{% endblock %}

</html>

templates/KITS/create_study.html
<!DOCTYPE html>
<html lang="en">
{% extends 'KITS/base.html' %}
{% block content %}
    <div class="container-fluid">
        <H2>Create Study</H2>
        <hr>

        <form method="POST">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Submit</button>
        </form>
    </div>
{% endblock %}

</html>

templates/KITS/home.html
<!DOCTYPE html>
<html lang="en">

{% extends 'KITS/base.html' %}
{% block content %}

    <body>
        <div class="d-flex align-items-center">
            <div class="container text-center" style="padding-top: 15%;">
            <h1>Welcome to KITS!</h1>
            <p>
                The Kit Inventory Tracking System application was created to help clinical trial sites <br />
                track their research kits used in the studies conducted therein.
            </p>

        {% if not user.is_authenticated %}
            <a class="btn btn-outline-success" href="{% url 'login' %}">Log In</a>
        {% endif %}
        </div>
        </div>

    </body>
{% endblock %}

</html>

templates/KITS/kit_addkitinstance.html
<!DOCTYPE html>
<html lang="en">
{% extends 'KITS/base.html' %}
{% block content %}

    <div class="container-fluid">
        <H2>Adding a "{{ kit_instance.type_name }}" kit for IRB Number: {{ kit_instance.IRB_number }}</H2>
        <hr>
        
        <form method="POST" class="kitinstance-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Add</button>
        </form>
    </div>
{% endblock %}

</html>

templates/KITS/kit_checkout.html
<!DOCTYPE html>
<html lang="en">
{% extends 'KITS/base.html' %}
{% block content %}

    <div class="container-fluid">
        <H2>Kit Checkout</H2>

        <hr>
        <form method="get">
            {{ kit_instance_filter.form }}
            <button class="btn btn-primary" type="submit">Search</button>
        </form>
        <hr>

        <table class="table table-striped table-bordered table-hover table-secondary">
            <thead>
                <tr class="bg-info">
                    <th>Kit Type ID</th>
                    <th>Kit ID</th>
                    <th>Kit Type</th>
                    <th>IRB #</th>
                    <th>Status</th>
                    <th>Expiration Date</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                {% for kitinstance in kitinstance %}
                    <td>{{ kitinstance.kit_id }}</td>
                    <td>{{ kitinstance.id }}</td>
                    <td>{{ kitinstance.kit.type_name }}</td>
                    <td>{{ kitinstance.kit.IRB_number }}</td>
                    <td>
                        {% if kitinstance.status == 'a' %}
                            <p><b style="color:darkgreen">Available</b></p>
                        {% elif kitinstance.status == 'c' %}
                            <p><b style="color:cadetblue">Checked-Out</b></p>
                        {% elif kitinstance.status == 'd' %}
                            <p><b style="color:black">Demolished</b></p>
                        {% elif kitinstance.status == 'e' %}
                            <p><b style="color:darkred">Expired</b></p>
                    {% endif %}
                    </td>
                    <td>{{ kitinstance.expiration_date }}</td>
                    <td>
                        {% if kitinstance.status == 'a' %}
                            <a href="{% url 'KITS:kitinstance_statusedit' pk=kitinstance.pk %}" class="btn-sm btn-success">Checkout</a>
                        {% endif %}

                        {% if kitinstance.status == 'a' %}
                            <a href="{% url 'KITS:kitinstance_demolish' pk=kitinstance.pk %}" class="btn-sm btn-danger">Demolish</a>
                        {% elif kitinstance.status == 'e' %}
                            <a href="{% url 'KITS:kitinstance_demolish' pk=kitinstance.pk %}" class="btn-sm btn-danger">Demolish</a>
                        {% endif %}

                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

</html>

templates/KITS/kit_delete.html
<!DOCTYPE html>
<html lang="en">
{% block body_block %}
    <h1>Delete {{ kit.id }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'KITS:kit_list' pk=kit.pk %} ">Cancel</a>
    </form>

{% endblock %}

</html>

templates/KITS/kit_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'KITS/base.html' %}
{% block content %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger" role="alert">
            {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="container-fluid">
        <H2>Types of Kits</H2>

        <hr>
        <form method="get">
            {{ kit_filter.form }}
            <button class="btn btn-primary" type="submit">Search</button>
        </form>
        <hr>

        <table class="table table-striped table-bordered table-secondary">
            <thead>
            <tr class="bg-info">
                <th>IRB Number</th>
                <th>Name of Kit</th>

                <th colspan="5">Actions</th>



            </tr>
            </thead>
            <tbody>
            {% for kit in kit %}
            <tr>
                <td>{{ kit.IRB_number }}</td>
                <td>{{ kit.type_name }}</td>


                <td>
                    <a href="{% url 'KITS:kit_addkitinstance' pk=kit.pk %}" class="btn-sm btn-success">Add Kit Instance</a>
                    <a href="{% url 'KITS:kit_edit' pk=kit.pk%}" class="btn-sm btn-warning">Edit</a>
                    <a href="{% url 'KITS:kit_delete' pk=kit.pk%}"
                        onclick="return confirm('Are you sure you want to delete Kit {{ kit.id }} under IRB#{{ kit.IRB_number }}? Do you have proper authorization?')"
                        class="btn-sm btn-danger">Delete</a>
                </td>


            </tr>
             {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'KITS:kit_addkittype' %}" class="btn btn-success">Add Kit Type</a>
        <a href="{% url 'KITS:kit_addlocation' %}" class="btn btn-success">Add Location</a>


    </div>
{% endblock %}
</html>

templates/KITS/report.html
<!DOCTYPE html>
<html lang="en">
{% extends 'KITS/base.html' %}
{% block content %}

    <div class="container-fluid">
        <H2>Reports</H2>
        <hr>

        <div class="container">
            <H5>Expired Kits</H5>

            <a href="{%  url 'KITS:report_expiredkits' %}" class="btn btn-success">List of all expired kits</a>
            <a href="{%  url 'KITS:report_expiredkits_studies' %}" class="btn btn-success">List of studies with expired kits</a>
            <a href="{%  url 'KITS:report_activestudies' %}" class="btn btn-success">Active and Less Active Studies</a>
            <a href="{%  url 'KITS:user_list' %}" class="btn btn-success">User and Studies</a>
        </div>
    </div>
{% endblock %}

</html>

templates/KITS/report_expiredkits_studies.html
<!DOCTYPE html>
<html lang="en">
{% extends 'KITS/base.html' %}
{% block content %}

    <div class="container-fluid">
        <H2>Reports - Studies with Expired Kits</H2>
        <hr>
        <table class="table table-striped table-bordered table-hover table-secondary">
            <thead>
                <tr class="bg-info">
                    <th>IRB</th>
                    <th>Pet Name</th>
                    <th>Number of Expired Kits</th>
                </tr>
            </thead>
            <tbody>
                {% for kit in kits %}
                <tr>
                    <td>{{ kit.IRB_number__IRB_number}}</td>
                    <td>{{ kit.IRB_number__pet_name }}</td>
                    <td>{{ kit.qty }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'KITS:export_studieswithexpiredkits' %}" class="btn btn-success">Export Report</a>
    </div>
{% endblock %}

</html>

templates/KITS/report_userstudies.html
<!DOCTYPE html>
<html lang="en">
{% extends 'KITS/base.html' %}
{% block content %}
    {% if request.user.is_staff %}
    <style>
    .column12 {
        float: left;
        margin: 8px;
        width: 35%;
    }

    .column3 {
        float: left;
        margin: 0;
        width: 27%;
    }

/* Clear floats after the columns */
    .row:after {
        content: "";
        display: table;
        clear: both;
    }
    </style>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="container-fluid">
        <H2>Reports - User Study Activity For: {{ user }}</H2>
        <hr>

        <form method="POST">
        {% csrf_token %}
        <h6>Filter by date range (MM-DD-YYYY):</h6>
        <span>From: </span><input type="text" name="startdate">
        <span>To: </span><input type="text" name="enddate">

        <button class="btn btn-primary" type="submit">Search</button>
        </form>

        <hr>
        <p> Studies Created, Changed, and Deleted From {{ startdate }} To {{ enddate }}</p>
        <hr>

        <div class="row">
            <div class="column12" style="margin-left: 12px;">
                <h3>Studies Created</h3>

                <table class="table table-striped table-bordered table-hover table-secondary">
                    <thead>
                        <tr class="bg-info">
                            <th>#</th>
                            <th>IRB</th>
                            <th>Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for instances in queryset %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ instances.IRB_number }}</td>
                                 <td>{{ instances.pet_name }}</td>
                             </tr>
                         {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="column12">
                <h3>Studies Changed</h3>

                <table class="table table-striped table-bordered table-hover table-secondary">
                    <thead>
                        <tr class="bg-info">
                            <th>#</th>
                            <th>IRB</th>
                            <th>Name</th>
                        </tr>
                    </thead>
                    <tbody>
                       {% for instances in queryset_changed %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ instances.IRB_number }}</td>
                                 <td>{{ instances.pet_name }}</td>
                             </tr>
                         {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="column3" style="background-color:white;">
                                <h3>Studies Deleted</h3>
                <table class="table table-striped table-bordered table-hover table-secondary">
                    <thead>
                        <tr class="bg-info">
                            <th>#</th>
                            <th>IRB</th>
                            <th>Name</th>
                        </tr>
                    </thead>
                    <tbody>
                       {% for instances in queryset_deleted %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ instances.IRB_number }}</td>
                                 <td>{{ instances.pet_name }}</td>
                             </tr>
                         {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
               <a href="{% url 'KITS:export_user' pk=user.pk%}" class="btn btn-success">Export Report</a>
    </div>
    {% endif %}
    {% if not request.user.is_staff %}
        <p>Not authorized to access this page.</p>
    {% endif %}
{% endblock %}
</html>

templates/KITS/study_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'KITS/base.html' %}
{% block content %}

    <div class="container-fluid">

        <H2 id="study_list">Studies</H2>

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success" role="alert">
                {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        <hr>
        <form method="get">
            {{ study_filter.form }}
            <button class="btn btn-primary" type="submit">Search</button>
        </form>
        <hr>

        <table class="table table-striped table-secondary table-bordered table-hover">
            <thead>
            <tr>
                <th>IRB Number</th>
                <th>Pet Name</th>
                <th>Study Status</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for study in studies %}
            <tr>
                <td>{{ study.IRB_number }}</td>
                <td>{{ study.pet_name }}</td>
                <td>{{ study.status }}</td>
                <td><a href="{% url 'KITS:study_detail' pk=study.pk %}" class="btn-sm btn-primary">Details</a>
                    {% if study.status != 'Closed' %}
                    <a href="{% url 'KITS:study_archive' pk=study.pk %}"
                        onclick="return confirm('Are you sure you want to archive {{ study.pet_name }}?')"
                        class="btn-sm btn-danger">Archive</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'KITS:create_study' %}" class="btn btn-success">Create a Study</a>
    </div>

{% endblock %}

</html>